ccflags-y += -Idrivers/soc/hisense/include

obj-$(CONFIG_HISENSE_BOOT_INFO)       += bootinfo.o
obj-y += productinfo.o
obj-$(CONFIG_SAVE_AWAKEN_EVENT)       += awaken_sys_event.o
obj-$(CONFIG_HISENSE_DEBUG_CTRL)      += his_debug_base.o his_debug_attrs.o
