#ifndef CUSTOM_FUNC_H__
#define CUSTOM_FUNC_H__
#define  ST_UPGRADE_FIRMWARE
#define  ST_MONITOR_THREAD
//#define  CONFIG_TOUCHSCREEN_SITRONIX_TS_GESTURE
#define  ST_TEST_RAW
//#define  ST_GLOVE_SWITCH_MODE
//#define  ST_CASES_SWITCH_MODE
//#define  ST_DEBUG_EN
#define  ST_MAX_TOUCHES  10
#endif /* CUSTOM_FUNC_H__ */
